name: Deploy

on:
  push:
    branches:
      - active

jobs:

  build:

    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - name: Bearings 1
        run: ls -la

      - name: Checkout
        uses: actions/checkout@v2

      - name: Bearings 2
        run: ls -la

      - name: Deployment
        id: deployment
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        with:
          flags: '-Izvrn --delete'
          src: 'lib/'
          ssh_options: '-p 222'
          dest: '${{secrets.SERVER_USER}}@${{secrets.SERVER_IP}}:/home/${{secrets.SERVER_USER}}/public_html/mastarija.com/'
