name: Deploy

on:
  push:
    branches:
      - active

jobs:
  build:
    env:
      CONFIG: "--enable-tests --test-show-details=direct"

    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.TARGET_PK }}
          known_hosts: 'placeholder:TODO'

      - name: Install Known Host
        run: ssh-keyscan -H ${{ secrets.TARGET_PK }} >> ~/.ssh/known_hosts

      - id: haskell
        name: Haskell Setup
        uses: haskell/actions/setup@v1
        with:
          ghc-version: "9.0.1"
          cabal-version: "3.6"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cabal Update
        run: cabal v2-update $CONFIG

      - name: Cabal Freeze
        run: cabal v2-freeze $CONFIG

      - name: Cache Builds
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.haskell.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-9.0.1-${{ hashFiles( 'cabal.project.freeze' ) }}
          restore-keys: ${{ runner.os }}-9.0.1-

      - name: Building Project
        run: cabal v2-build all $CONFIG

      - name: Building Website
        run: cabal exec demon

      - name: Uploading Website
        run: rsync -Izvrn -e ssh --delete ./www/ ${{TARGET_USER}}@${{TARGET_HOST}}:/home/reygoch/public_html/mastarija.com/
